version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:mysql://db:3306/steam-alert-db?createDatabaseIfNotExist=true
      - DB_USER=root
      - DB_PASSWORD=#YOUR DB PASS
      - BOT_TOKEN= # YOUR BOT TOKEN
      - BOT_CREATOR_ID= # YOUR TELEGRAM ID
      - STEAM_API_KEY= # YOUR STEAM API KEY

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=steam-alert-db
      - MYSQL_ROOT_PASSWORD= #YOUR DB PASS