version: '3.8'
services:
  app:
    container_name: steam-alert
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN= # YOUR BOT TOKEN
      - BOT_CREATOR_ID= # YOUR TELEGRAM ID
      - STEAM_API_KEY= # YOUR STEAM API KEY
    restart: always
